export const bibleBooks = [
  { id: 'gen', name: 'Genesis', chapters: 50 },
  { id: 'exod', name: 'Exodus', chapters: 40 },
  { id: 'lev', name: 'Leviticus', chapters: 27 },
  { id: 'num', name: 'Numbers', chapters: 36 },
  { id: 'deut', name: 'Deuteronomy', chapters: 34 },
  { id: 'josh', name: 'Joshua', chapters: 24 },
  { id: 'judg', name: 'Judges', chapters: 21 },
  { id: 'ruth', name: 'Ruth', chapters: 4 },
  { id: '1sam', name: '1 Samuel', chapters: 31 },
  { id: '2sam', name: '2 Samuel', chapters: 24 },
  { id: '1kgs', name: '1 Kings', chapters: 22 },
  { id: '2kgs', name: '2 Kings', chapters: 25 },
  { id: '1chr', name: '1 Chronicles', chapters: 29 },
  { id: '2chr', name: '2 Chronicles', chapters: 36 },
  { id: 'ezra', name: 'Ezra', chapters: 10 },
  { id: 'neh', name: 'Nehemiah', chapters: 13 },
  { id: 'esth', name: 'Esther', chapters: 10 },
  { id: 'job', name: 'Job', chapters: 42 },
  { id: 'ps', name: 'Psalms', chapters: 150 },
  { id: 'prov', name: 'Proverbs', chapters: 31 },
  { id: 'eccl', name: 'Ecclesiastes', chapters: 12 },
  { id: 'song', name: 'Song of Solomon', chapters: 8 },
  { id: 'isa', name: 'Isaiah', chapters: 66 },
  { id: 'jer', name: 'Jeremiah', chapters: 52 },
  { id: 'lam', name: 'Lamentations', chapters: 5 },
  { id: 'ezek', name: 'Ezekiel', chapters: 48 },
  { id: 'dan', name: 'Daniel', chapters: 12 },
  { id: 'hos', name: 'Hosea', chapters: 14 },
  { id: 'joel', name: 'Joel', chapters: 3 },
  { id: 'amos', name: 'Amos', chapters: 9 },
  { id: 'obad', name: 'Obadiah', chapters: 1 },
  { id: 'jona', name: 'Jonah', chapters: 4 },
  { id: 'mic', name: 'Micah', chapters: 7 },
  { id: 'nah', name: 'Nahum', chapters: 3 },
  { id: 'hab', name: 'Habakkuk', chapters: 3 },
  { id: 'zeph', name: 'Zephaniah', chapters: 3 },
  { id: 'hag', name: 'Haggai', chapters: 2 },
  { id: 'zech', name: 'Zechariah', chapters: 14 },
  { id: 'mal', name: 'Malachi', chapters: 4 },
  { id: 'matt', name: 'Matthew', chapters: 28 },
  { id: 'mark', name: 'Mark', chapters: 16 },
  { id: 'luke', name: 'Luke', chapters: 24 },
  { id: 'john', name: 'John', chapters: 21 },
  { id: 'acts', name: 'Acts of the Apostles', chapters: 28 },
  { id: 'rom', name: 'Romans', chapters: 16 },
  { id: '1cor', name: '1 Corinthians', chapters: 16 },
  { id: '2cor', name: '2 Corinthians', chapters: 13 },
  { id: 'gal', name: 'Galatians', chapters: 6 },
  { id: 'eph', name: 'Ephesians', chapters: 6 },
  { id: 'phil', name: 'Philippians', chapters: 4 },
  { id: 'col', name: 'Colossians', chapters: 4 },
  { id: '1thess', name: '1 Thessalonians', chapters: 5 },
  { id: '2thess', name: '2 Thessalonians', chapters: 3 },
  { id: '1tim', name: '1 Timothy', chapters: 6 },
  { id: '2tim', name: '2 Timothy', chapters: 4 },
  { id: 'titus', name: 'Titus', chapters: 3 },
  { id: 'phlm', name: 'Philemon', chapters: 1 },
  { id: 'heb', name: 'Hebrews', chapters: 13 },
  { id: 'jas', name: 'James', chapters: 5 },
  { id: '1pet', name: '1 Peter', chapters: 5 },
  { id: '2pet', name: '2 Peter', chapters: 3 },
  { id: '1john', name: '1 John', chapters: 5 },
  { id: '2john', name: '2 John', chapters: 1 },
  { id: '3john', name: '3 John', chapters: 1 },
  { id: 'jude', name: 'Jude', chapters: 1 },
  { id: 'rev', name: 'Revelation', chapters: 22 },
];
