export const books = [
  { id: 1, name: "Genesis", chapters: 50, abbreviation: "Gen" },
  { id: 2, name: "Exodus", chapters: 40, abbreviation: "Exo" },
  { id: 3, name: "Leviticus", chapters: 27, abbreviation: "Lev" },
  { id: 4, name: "Numbers", chapters: 36, abbreviation: "Num" },
  { id: 5, name: "Deuteronomy", chapters: 34, abbreviation: "Deut" },
  { id: 6, name: "Joshua", chapters: 24, abbreviation: "Josh" },
  { id: 7, name: "Judges", chapters: 21, abbreviation: "Judg" },
  { id: 8, name: "Ruth", chapters: 4, abbreviation: "Ruth" },
  { id: 9, name: "1 Samuel", chapters: 31, abbreviation: "1 Sam" },
  { id: 10, name: "2 Samuel", chapters: 24, abbreviation: "2 Sam" },
  { id: 11, name: "1 Kings", chapters: 22, abbreviation: "1 Kings" },
  { id: 12, name: "2 Kings", chapters: 25, abbreviation: "2 Kings" },
  { id: 13, name: "1 Chronicles", chapters: 29, abbreviation: "1 Chron" },
  { id: 14, name: "2 Chronicles", chapters: 36, abbreviation: "2 Chron" },
  { id: 15, name: "Ezra", chapters: 10, abbreviation: "Ezra" },
  { id: 16, name: "Nehemiah", chapters: 13, abbreviation: "Neh" },
  { id: 17, name: "Esther", chapters: 10, abbreviation: "Esth" },
  { id: 18, name: "Job", chapters: 42, abbreviation: "Job" },
  { id: 19, name: "Psalms", chapters: 150, abbreviation: "Psalm" },
  { id: 20, name: "Proverbs", chapters: 31, abbreviation: "Prov" },
  { id: 21, name: "Ecclesiastes", chapters: 12, abbreviation: "Eccles" },
  { id: 22, name: "Song of Solomon", chapters: 8, abbreviation: "Song" },
  { id: 23, name: "Isaiah", chapters: 66, abbreviation: "Isa" },
  { id: 24, name: "Jeremiah", chapters: 52, abbreviation: "Jer" },
  { id: 25, name: "Lamentations", chapters: 5, abbreviation: "Lam" },
  { id: 26, name: "Ezekiel", chapters: 48, abbreviation: "Ezek" },
  { id: 27, name: "Daniel", chapters: 12, abbreviation: "Dan" },
  { id: 28, name: "Hosea", chapters: 14, abbreviation: "Hos" },
  { id: 29, name: "Joel", chapters: 3, abbreviation: "Joel" },
  { id: 30, name: "Amos", chapters: 9, abbreviation: "Amos" },
  { id: 31, name: "Obadiah", chapters: 1, abbreviation: "Obad" },
  { id: 32, name: "Jonah", chapters: 4, abbreviation: "Jonah" },
  { id: 33, name: "Micah", chapters: 7, abbreviation: "Micah" },
  { id: 34, name: "Nahum", chapters: 3, abbreviation: "Nah" },
  { id: 35, name: "Habakkuk", chapters: 3, abbreviation: "Hab" },
  { id: 36, name: "Zephaniah", chapters: 3, abbreviation: "Zeph" },
  { id: 37, name: "Haggai", chapters: 2, abbreviation: "Hag" },
  { id: 38, name: "Zechariah", chapters: 14, abbreviation: "Zech" },
  { id: 39, name: "Malachi", chapters: 4, abbreviation: "Mal" },
  { id: 40, name: "Matthew", chapters: 28, abbreviation: "Matt" },
  { id: 41, name: "Mark", chapters: 16, abbreviation: "Mark" },
  { id: 42, name: "Luke", chapters: 24, abbreviation: "Luke" },
  { id: 43, name: "John", chapters: 21, abbreviation: "John" },
  { id: 44, name: "Acts", chapters: 28, abbreviation: "Acts" },
  { id: 45, name: "Romans", chapters: 16, abbreviation: "Rom" },
  { id: 46, name: "1 Corinthians", chapters: 16, abbreviation: "1 Cor" },
  { id: 47, name: "2 Corinthians", chapters: 13, abbreviation: "2 Cor" },
  { id: 48, name: "Galatians", chapters: 6, abbreviation: "Gal" },
  { id: 49, name: "Ephesians", chapters: 6, abbreviation: "Eph" },
  { id: 50, name: "Philippians", chapters: 4, abbreviation: "Phil" },
  { id: 51, name: "Colossians", chapters: 4, abbreviation: "Col" },
  { id: 52, name: "1 Thessalonians", chapters: 5, abbreviation: "1 Thess" },
  { id: 53, name: "2 Thessalonians", chapters: 3, abbreviation: "2 Thess" },
  { id: 54, name: "1 Timothy", chapters: 6, abbreviation: "1 Tim" },
  { id: 55, name: "2 Timothy", chapters: 4, abbreviation: "2 Tim" },
  { id: 56, name: "Titus", chapters: 3, abbreviation: "Titus" },
  { id: 57, name: "Philemon", chapters: 1, abbreviation: "Philem" },
  { id: 58, name: "Hebrews", chapters: 13, abbreviation: "Heb" },
  { id: 59, name: "James", chapters: 5, abbreviation: "James" },
  { id: 60, name: "1 Peter", chapters: 5, abbreviation: "1 Pet" },
  { id: 61, name: "2 Peter", chapters: 3, abbreviation: "2 Pet" },
  { id: 62, name: "1 John", chapters: 5, abbreviation: "1 John" },
  { id: 63, name: "2 John", chapters: 1, abbreviation: "2 John" },
  { id: 64, name: "3 John", chapters: 1, abbreviation: "3 John" },
  { id: 65, name: "Jude", chapters: 1, abbreviation: "Jude" },
  { id: 66, name: "Revelation", chapters: 22, abbreviation: "Rev" },
];
